/** Лимиты сессий */
export const SESSION_LIMITS = {
  MIN_ANALYSTS: 2,
  MAX_ANALYSTS: 6,
  DEFAULT_ANALYSTS: 3,
  MIN_ROUNDS: 1,
  MAX_ROUNDS: 15,
  DEFAULT_MAX_ROUNDS: 5,
  DEFAULT_MAX_RESEARCH_CALLS: 5,
  MAX_RESEARCH_CALLS: 10,
  DEFAULT_MAX_IDEAS_FINAL: 3,
  MAX_IDEAS_FINAL: 10,
} as const;
